### ISSUE TITLE
Need demo?

### ISSUE THREAD

**Issue by suriyaJaay** [bpred754/augeo#39]
could you pls upload demo of this project?

**Comment by bpred754** [comment]
Hi suriyaJaay, augeo is currently live, albeit in an alpha state. You can sign up and explore the site at https://augeo.io. Thanks for reaching out!

**Comment by bpred754** [comment]
Sorry, the link above does not work. Please try https://www.augeo.io

**Comment by suriyaJaay** [comment]
@bpred754 after signing in your app. the dark overlay doesn't allow me access app. do i need confirm via link. if so i don't receive any link. pls find the blow image. 
![ag](https://cloud.githubusercontent.com/assets/19813670/20129167/de24357a-a673-11e6-8d65-b1c617212bd0.PNG)

**Comment by bpred754** [comment]
Did you get a welcome screen? If so, you need to select the "continue" button. If not, can you try logging out and logging back in. You can do that by first clicking the icon in the top right corner of the screen and then selecting "Logout". Let me know how it goes. Sorry for the troubles.. it's still a new app :)

**Comment by suriyaJaay** [comment]
@bpred754 now its working fine. am in. thank you. just did authenticate with twitter.
after getting in what should i do next?
then tell me i could access the "technology" part from dashboard. 


(i would like to contribute in UI part. can i?)

**Comment by bpred754** [comment]
Awesome, that's great :) right now, there isn't much you can do within the app itself, just search for people using the leaderboards screen and view the different activities that they have performed. This isn't very helpful though since the app is so new and there aren't any people :)

I would love some help with the UI, however at this moment I don't have any specific tasks. Currently I am working on adding a Fitbit interface that will contribute to the Fitness skill. This is almost done, so don't need help there.. after Fitbit I want to add a feature that will allow users to "flag" posts to encourage user engagement within the app itself. At this point, I would suggest pulling the code and getting familiar with the design. I am using the MEAN stack. There is also some useful information in the wiki portion of this repository. Probably a good idea to check that out as well. It contains ideas I have for future features. Let me know if you have any questions!

**Comment by suriyaJaay** [comment]
yeah sure. let me go through it completely and come back. what can i do with this. 

and thanks for your quick response.
